networks:
# servers
  -
    name: web
    ip: 65.208.228.223
    type: linux
  -
    name: dns
    ip: 192.168.0.12
    type: linux
  -
    name: mail
    ip: 192.168.0.13
    type: linux
# clients
  -
    name: win01
    ip: 145.254.160.237
    type: windows
  -
    name: win02
    ip: 192.168.0.102
    type: windows
  -
    name: win03
    ip: 192.168.0.103
    type: windows